server:
  port: 8080

spring:
  application:
    name: house-hold-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-user
          uri: lb://house-hold-auth-user
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
