# 无 Nacos 时使用固定地址转发
spring:
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      routes:
        - id: auth-user-auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: auth-user-user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: auth-user-family
          uri: http://localhost:8081
          predicates:
            - Path=/family/**
        - id: wealth
          uri: http://localhost:8082
          predicates:
            - Path=/wealth/**
