-- 迭代一：用户表（服务启动时自动执行，CREATE TABLE IF NOT EXISTS 保证可重复执行）
CREATE TABLE IF NOT EXISTS user_base (
  id BIGINT PRIMARY KEY COMMENT '用户ID',
  username VARCHAR(64) NOT NULL COMMENT '用户名',
  password_hash VARCHAR(128) NOT NULL COMMENT '密码哈希',
  name VARCHAR(64) DEFAULT NULL COMMENT '姓名',
  birthday DATE NOT NULL COMMENT '生日',
  email VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  phone VARCHAR(32) DEFAULT NULL COMMENT '手机',
  family_id BIGINT DEFAULT NULL COMMENT '家庭ID，迭代二使用',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_username (username),
  KEY idx_family_id (family_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 迭代二：家庭表
CREATE TABLE IF NOT EXISTS family (
  id BIGINT PRIMARY KEY COMMENT '家庭ID',
  name_alias VARCHAR(64) NOT NULL COMMENT '家庭别名',
  country VARCHAR(64) NOT NULL DEFAULT '' COMMENT '国家',
  province VARCHAR(64) NOT NULL DEFAULT '' COMMENT '省份',
  city VARCHAR(64) NOT NULL DEFAULT '' COMMENT '城市',
  street VARCHAR(256) NOT NULL DEFAULT '' COMMENT '街道',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭表';

-- 迭代二：家庭成员角色表
CREATE TABLE IF NOT EXISTS family_member_role (
  id BIGINT PRIMARY KEY COMMENT '主键',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  family_id BIGINT NOT NULL COMMENT '家庭ID',
  role VARCHAR(32) NOT NULL DEFAULT 'OTHER' COMMENT '角色:HUSBAND,WIFE,CHILD,OTHER',
  joined_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_user_family (user_id, family_id),
  KEY idx_family_id (family_id),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭成员角色表';
